# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\"\x90\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x11\n\tpublisher\x18\x04 \x01(\t\x12\x16\n\x0epublished_date\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x02\x12\x12\n\npage_count\x18\x07 \x01(\x05\x12\r\n\x05genre\x18\x08 \x01(\t\"#\n\x06\x41uthor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x62io\x18\x02 \x01(\t\"@\n\tPublisher\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\"Z\n\x08\x43ustomer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\"|\n\x05Order\x12\x14\n\x0corder_number\x18\x01 \x01(\t\x12\x1b\n\x08\x63ustomer\x18\x02 \x01(\x0b\x32\t.Customer\x12\x14\n\x05items\x18\x03 \x03(\x0b\x32\x05.Book\x12\x12\n\norder_date\x18\x04 \x01(\t\x12\x16\n\x0eshiping_status\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=15
  _globals['_BOOK']._serialized_end=159
  _globals['_AUTHOR']._serialized_start=161
  _globals['_AUTHOR']._serialized_end=196
  _globals['_PUBLISHER']._serialized_start=198
  _globals['_PUBLISHER']._serialized_end=262
  _globals['_CUSTOMER']._serialized_start=264
  _globals['_CUSTOMER']._serialized_end=354
  _globals['_ORDER']._serialized_start=356
  _globals['_ORDER']._serialized_end=480
# @@protoc_insertion_point(module_scope)
