# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"\x1e\n\x0eRequestMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0fResponseMessage\x12\x0e\n\x06result\x18\x01 \x01(\t2Y\n\x10StreamingService\x12\x45\n\nStreamData\x12\x19.streaming.RequestMessage\x1a\x1a.streaming.ResponseMessage(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTMESSAGE']._serialized_start=30
  _globals['_REQUESTMESSAGE']._serialized_end=60
  _globals['_RESPONSEMESSAGE']._serialized_start=62
  _globals['_RESPONSEMESSAGE']._serialized_end=95
  _globals['_STREAMINGSERVICE']._serialized_start=97
  _globals['_STREAMINGSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
